### PR TITLE
added effective_url support

### PR DESCRIPTION
**Pull request by hthabet**
### Context
@hannesl and I encountered this issue https://github.com/php-vcr/php-vcr/issues/227. @hannesl's solution was to change elasticsearch codebase. However, I thought it is best to add the change to php-vcr.

### What has been done

- 439a96d Added effective_url field in the Response object

### How to test

- Please see https://github.com/php-vcr/php-vcr/issues/227
- Run tests

### CODE REVIEW

**Comment by monobook** [comment]
@renatomefi ping? :)

**Comment by BozanicJosip** [comment]
Any ideas if this will be merged?

**Comment by whikloj** [comment]
Ha, browsing for a new issue I totally missed this PR and the associated ticket when I ran into the same problem and  opened issue #363 and PR #364.

As your PR has been wasting for 4 years, I'll assume this isn't getting fixed.

**Comment by higidi** [comment]
Since we're persisting the whole curl info array starting with #300 this should be redundant.

**Pull request closed without merging**
