### PR TITLE
chore: Ignore composer.lock

### PR DESCRIPTION
**Pull request by pvgnd**
### Context

composer.lock should never been commited to Git repository

### What has been done

- composer.lock has been added to .gitignore

### CODE REVIEW

**Comment by JeroenVanOort** [comment]
Didn't you mean to also remove composer.lock from the repository?

**Comment by pvgnd** [comment]
oh right, I didn't notice the root composer.lock
My first intention was to exclude composer.lock created in integration tests dir

**Comment by JeroenVanOort** [comment]
At this moment, I expect Travis to fail, but not because of your change. Please have a little more patience while I'm figuring out https://github.com/php-vcr/php-vcr/issues/332 .

**Review by JeroenVanOort — APPROVED** [review]

**Comment by JeroenVanOort** [comment]
If you could rebase against current master, I will merge asap.

**Comment by pvgnd** [comment]
done

**Pull request merged**
