### PR TITLE
call_user_func doesn't work in this context with private or protected…

### PR DESCRIPTION
**Pull request by alnorth**
### Context

Calling `call_user_func` in CurlHelper.php doesn't work when `CURLOPT_HEADERFUNCTION` or `CURLOPT_WRITEFUNCTION` have been set with private or protected methods. This has caused issues when using php-vcr with PayPal's PHP SDK (https://github.com/paypal/PayPal-PHP-SDK/issues/1057). 

### What has been done

- I've added a wrapper function around `call_user_func` that attempts to detect when this scenario is encountered and then works around it using some reflection magic.

### How to test

- Unit tests have been added, so it can be tested in the usual way.

### CODE REVIEW

**Comment by specialtactics** [comment]
Hey @JeroenVanOort is it possible to take a look at this? It's a huge blocker for us, and we are having to maintain our own fork of this project as a result.

I can see it can no longer be merged, so I'm happy to do a new PR with these changes, if you can have a look and get it merged and tagged.

**Comment by alnorth** [comment]
It wasn't too hard to rebase the PR onto the current master branch. Now we just need to wait for Travis CI to catch up!

**Comment by JeroenVanOort** [comment]
I'll merge and release a new version as soon as Travis does it's thing. I hope it'll be before Christmas ;-)

**Comment by JeroenVanOort** [comment]
Although Travis hasn't completed yet, there seem to be some problems.

**Comment by alnorth** [comment]
Seems to be some simple code formatting stuff. I'll take care of it now.

**Comment by specialtactics** [comment]
@JeroenVanOort If i pull current master, those tests which are failing on the php 7.3/7.4 builds fail for me currently out of the box, I am not sure how or why it got to this state, but it seems like master isn't passing tests?

For this one, it's just some cs which @alnorth needs to fix.
https://travis-ci.org/github/php-vcr/php-vcr/jobs/744926494

**Comment by JeroenVanOort** [comment]
For me, the tests on master work just fine, in my local environment. I just pushed a branch to see how Travis handles the current master.

**Comment by specialtactics** [comment]
Thanks guys, I think once that issue is resolved, this will be good to go!

**Comment by specialtactics** [comment]
@alnorth if you pull and merge master into your branch, hopefully it will work now.

**Comment by JeroenVanOort** [comment]
Or even better: rebase ;-)

**Comment by alnorth** [comment]
Rebased and squashed the commits 😄

**Comment by specialtactics** [comment]
Really big thanks to everyone for getting this across the line! @alnorth @JeroenVanOort - it definitely makes a big difference to us (and probably others who have been maintaining their own outdated forks).

Could you please tag master?

**Pull request merged**
