### PR TITLE
[RFC] Allow symfony/yaml and symfony/event-dispatcher v4.0 as dependency

### PR DESCRIPTION
**Pull request by tiagobrito**
### Context
Symfony 4 was released

### What has been done

- Allow users to use symfony/yaml version 4 as dependency
- Allow users to use symfony/event-dispatcher version 4 as dependency

### CODE REVIEW

**Comment by kornrunner** [comment]
+1 for merging this in and tagging as a patch

**Comment by tiagobrito** [comment]
The build is failing due to `PHP_CS_FIXER` but I didn't touch on PHP code :/

**Comment by renatomefi** [comment]
@tiagobrito indeed it's because we introduced the cs-fixer just a while ago.
Do you want to apply the fixes so I can merge it?

Thank you for your contribution!

**Comment by tiagobrito** [comment]
@renatomefi yes I can apply the fixes

**Comment by renatomefi** [comment]
Sounds great, thank you @tiagobrito

**Comment by renatomefi** [comment]
@tiagobrito @kornrunner you can update to vcr 1.4.2! 💯

**Comment by tiagobrito** [comment]
Thanks for your work. if you need something else, let me know.

**Pull request merged**
