### PR TITLE
vcr hooks implementation

### PR DESCRIPTION
**Pull request by aaa2000**
The implementation of new features is more easier with these hooks.
https://relishapp.com/vcr/vcr/v/2-9-3/docs/hooks

### CODE REVIEW

**Comment by K-Phoen** [comment]
Hell yeah!
It would simplify the bundle's code and even allow a few nice things like telling the user which requests were replayed and which ones were not.

I didn't review @aaa2000's code but I'm definitely :+1: for events.

**Comment by tylercollier** [comment]
@adri You asked if YAGNI. The Ruby VCR version has this, why wouldn't we want it here? Hooks are perfect for the "not everyone will need it, but some will" case.

**Comment by adri** [comment]
@aaa2000 Could you please rebase on master?

**Comment by aaa2000** [comment]
Done

**Comment by adri** [comment]
Merged. Great work, thank you @aaa2000.

**Comment by aaa2000** [comment]
Thanks, but I had the symfony/event-dispatcher dependency because Guzzle use it. But now, the dependency with Guzzle was removed, maybe later you should reimplement a VCR event dispatcher.

**Comment by adri** [comment]
Because you worried about dependency conflicts with other projects? 
I suspect the EventDispatcher to be pretty stable by now.

**Comment by K-Phoen** [comment]
Bam, the VCRBundle has been updated to use the new hooks!

**Comment by aaa2000** [comment]
yes, dependency conflicts with other projects when a version 3 of EventDispatcher will be publish.

**Pull request merged**
