### PR TITLE
Also test against PHP 7.2

### PR DESCRIPTION
**Pull request by arubacao**
### Context
PHP `7.2` has been released. 

### What has been done

- Updated the travis.yml file

### How to test

- Let travis do the job

### CODE REVIEW

**Comment by renatomefi** [comment]
Hey @tiagobrito thanks for the contribution!
It's not really necessary to test the lower reqs for 7.2, if we find the lowest compatible version of each library using 7.2 we are gonna limit it too much and not gain a lot from it! I do believe people using 7.2 has updated libraries.

We can introduce the lowest 7.2 during the next minor/major!

**Comment by tiagobrito** [comment]
@arubacao You should rebase this with master, the php cs fixer is already working there.
Thanks for your contribution.

**Comment by arubacao** [comment]
@renatomefi @tiagobrito done :)

**Comment by renatomefi** [comment]
Thanks so much @arubacao

**Pull request merged**
