### PR TITLE
Throw VCRException when cURL request fails

### PR DESCRIPTION
**Pull request by justinstern**
Prior to this change, a cURL failure in which `curl_exec()` returns `false`, was resulting in a less than helpful "Undefined offset: 1" exception being thrown from the [`explode()` call in `HttpUtil.parseResponse()`](https://github.com/php-vcr/php-vcr/blob/master/src/VCR/Util/HttpUtil.php#L66)

This change throws a `VCRException` with the underlying curl error and error number, making debugging that much easier

### CODE REVIEW

**Comment by adri** [comment]
Thanks a lot for the contribution! I'm very sorry for the late answer.

Could you please add a test testing the`VCRException`? Then we can make sure that this behaviour will stay in the future.

**Comment by justinstern** [comment]
sure thing

**Comment by justinstern** [comment]
@adri test case added! looking good now?

**Comment by justinstern** [comment]
@renatomefi apologies for the delay here. I've pushed the fix for the php-cs

Now the failures seem to be from this external WSDL that a ton of tests rely on and which no longer seems to be available:

> HP Fatal error:  SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL' : failed to load external entity "http://wsf.cdyne.com/WeatherWS/Weather.asmx?WSDL"

I had the same failures when running the test suite locally, and sure enough that WSDL page returns an error at the moment. So I'm not sure what you want to do about that, but as far as my PR here is concerned, I think things are good?

**Comment by renatomefi** [comment]
@justinstern Thanks for it!

Indeed the soap webservice is failing, I'm trying contact with them, if it doesn't help we'll have to find a new one and replace in the tests! :/ (Happened once already with another webservice)

For me the PR looks good, just have to check with @adri if he sees any other impact in the current usage of the library.

Thanks again and have a nice day!

**Comment by justinstern** [comment]
@renatomefi awesome, you too! and thanks also for such a sweet library!

**Comment by allejo** [comment]
Any updates on this?

**Comment by Tobion** [comment]
This bug is really annoying. But conceptually, shouldn't VCR throw the same error as the library it is replacing?. So a guzzle exception for example and not a custom one. Otherwise a try catch will not work if a different exception is thrown suddenly.

**Comment by renatomefi** [comment]
@justinstern we've fixed the tests, could you rebase your PR? I'm considering this for php-vcr 1.4.0

**Comment by justinstern** [comment]
@renatomefi well, I know I missed the ⛵️ on v1.4.0 by a bit... Any interest in including this in the next release? I've merged in `master` and everything seems to be passing now

**Comment by moufmouf** [comment]
Just noticed this PR. I worked on a very very similar PR: #258 .
#258 does exactly the same thing but it also catches the Exception in Soap and Curl handlers in order to mimic the cURL or SoapClient error handling.

@renatomefi : you can close this PR if you merge #258.

**Comment by JeroenVanOort** [comment]
Since https://github.com/php-vcr/php-vcr/pull/258 has been merged as part of https://github.com/php-vcr/php-vcr/pull/259, I think this PR can be closed.

**Pull request closed without merging**
