### PR TITLE
Parse duplicate headers properly

### LINKED ISSUE #123: Duplicate response headers are being dropped
Duplicate response headers are [allowed under certain conditions](http://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable). Duplicate values are dropped by PHP VCR (actually, all but the last value are lost).

### PR DESCRIPTION
**Pull request by justincy**
Fixes #123

### CODE REVIEW

**Comment by justincy** [comment]
@adri Ready for review.

**Comment by adri** [comment]
Nice! I think the best solution would be to store the exact request. 

For now this is good 👍

**Comment by adri** [comment]
I'll release with some other stuff soon.

**Comment by adri** [comment]
Released [1.2.5](https://github.com/php-vcr/php-vcr/releases/tag/1.2.5)

**Pull request merged**
