### PR TITLE
Support for Symfony 6

### PR DESCRIPTION
**Pull request by nicodemuz**
### Context
Add support for Symfony 6 dependencies.

### What has been done

- Changes in composer.json

### CODE REVIEW

**Review by ecourtial — DISMISSED** [review]

**Comment by edudobay** [comment]
Is there any chance this will get merged soon? Is this project still active?

**Comment by royharink** [comment]
Any chance this gets merged? There is also an issue related to this: https://github.com/php-vcr/php-vcr/issues/367

**Comment by ecourtial** [comment]
@JeroenVanOort 😃 ?

**Comment by specialtactics** [comment]
Hey guys feel free to use our fork, we're a company so we will likely look after this package for some time.
https://github.com/CoverGenius/php-vcr

**Comment by higidi** [comment]
Can you pls rebase it onto the current master and i'll merge it.

**Comment by nicodemuz** [comment]
@higidi I have rebased it.

**Pull request merged**
