### PR TITLE
New PHP 7, fully type-hinted version

### PR DESCRIPTION
**Pull request by moufmouf**
### Context

As proposed in #256 , here is a complete PR to modernize PHP-VCR.

### What has been done

- Made PHP 7.2 the minimum version
- Merged a few pending PRs (#258 and #210)
- Upgraded to PHPunit 7.
- Removed the lapistano/proxy-object library.
- Fixed all PHPStan declared errors up to the maximum level (level 7)
- Added PHP 7.1 type-hints absolutely everywhere (thanks to thecodingmachine/phpstan-strict-rules that detects missing type hints).

I worked on my fork. You can have a look at the various PRs I did on my own fork here: 

- https://github.com/moufmouf/php-vcr/pull/1
- https://github.com/moufmouf/php-vcr/pull/3
- https://github.com/moufmouf/php-vcr/pull/4
- https://github.com/moufmouf/php-vcr/pull/5

I tried to keep the commits as atomic as possible.
I added a few unit tests and I also remove a few unit tests that were useless because they were checking for types (and the type hint does that automatically now).

We must still decide if we want to target a 1.5 or a 2.0 version with this PR.
If we go for the 2.0, I have a few ideas that are clearly breaking changes. For instance, it would be safer to declare a "RequestMatcherInterface" that matches 2 requests (so far, a request matcher is a simple callable that cannot by type hinted).

Note: all the tests are passing but I will test this PR properly on a real-life project next week. Meanwhile, let's keep the [WIP] flag for safety :)

### About the removal of lapistano/proxy-object:

It was used to access protected properties of objects and was abandonned (project did not move in 3 years), and incompatible with PHPUnit 7.
I replaced it with simple anonymous classes that extend the object that was previously proxied and that have an extra public getter on the protected properties/methods I want to access.
So I replaced a complete library with a simple new language feature added in PHP 7 (anonymous classes). PHP7 FTW!

### CODE REVIEW

**Comment by pfuhrmann** [comment]
Any activity here @moufmouf ?

**Comment by gwlortscher** [comment]
This is awesome! Super excited to see this come to life.

**Comment by moufmouf** [comment]
Actually, this is ready to be merged.
We have extensively tested this on a real-life project and it works pretty well.

We must decide if we merge this in a 1.5 or a 2.0 branch (ping @renatomefi )
If we merge in a 2.0 branch, I would advocate for applying some more refactoring (especially I'd like to create a "RequestMatcherInterface")

Anyway, you can already start testing this, the code is pretty stable.

**Comment by moufmouf** [comment]
Ping @renatomefi . Any chance we can discuss this PR? This is a major refactoring of PHP-VCR.

**Comment by kornrunner** [comment]
I'm looking forward to merging this. Would you consider adding 7.4 to travis as well (perhaps under allow failures)? 7.4 is in feature freeze state and I'm trying to prepare for it before it rolls out.

If you wish I can open a new PR - although it's likely more suited to be included within this one. 

Thanks!

**Comment by gwlortscher** [comment]
@renatomefi this library has been amazing and I'd love to see this great work by @moufmouf merged into a new release 🙏

**Comment by MrRio** [comment]
Would love to see this merged 👍

**Comment by moufmouf** [comment]
@kornrunner Thanks! => Added PHP 7.4snapshot to Travis. Seems it is failing for some obscure reason. Maybe we can wait until a release candidate before diving in the details of why it is failing.

@renatomefi I updated the PR with the latest changes in the dependencies

- Fixed a breaking change introduced in symfony/event-dispatcher in Symfony 4.3 (believe it or not, there is a breaking change in the minor version). Note: PHP-VCR 1.x is probably impacted too by this issue
- Fixed coding style because PHP-CS-Fixer new version fixes code a bit differently

**Comment by renatomefi** [comment]
Hey @moufmouf!

I think it's impossible for me to review this, I think we can create a 2.0 branch and do a pre-release tag, thus the people here can also help you on validating the changes!

Does that sound good?

Thanks again for all the hard work and interest!

**Comment by moufmouf** [comment]
Hey @renatomefi ,

Sounds good, definitely!
If you create a pre-release, please tag it "alpha" rather that "RC".

I refrained from introducing breaking changes in this PR, but I have a few ideas (particularly regarding refactoring request matchers) that might require some breaking changes. I'll propose those in a different PR.

**Comment by atymic** [comment]
Hey team, any updates on this? Looks awesome and i'd love to try it out.
Happy to help out if you need on the PR as well.

**Comment by JeroenVanOort** [comment]
I've brought this up to speed with the current master. I've still got some work to do, but I'm planning on using this PR as the base for the 1.5 branch.

**Pull request merged**
